AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
